import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputJs = resolve(root, ".wrangler", "mailflow-vendor.js");
const outputTs = resolve(root, "src", "vendor.generated.ts");

mkdirSync(dirname(outputJs), { recursive: true });

execFileSync(
  resolve(root, "node_modules", ".bin", "esbuild"),
  [resolve(root, "src", "vendor.entry.js"), "--bundle", "--format=iife", "--target=es2022", "--minify", `--outfile=${outputJs}`],
  { cwd: root, stdio: "inherit" }
);

const js = readFileSync(outputJs, "utf8");
writeFileSync(outputTs, `// Generated by npm run build:vendor. Do not edit by hand.\nexport const APP_VENDOR_JS = ${JSON.stringify(js)};\n`);
