import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputCss = resolve(root, ".wrangler", "mailflow-app.css");
const outputTs = resolve(root, "src", "styles.generated.ts");

mkdirSync(dirname(outputCss), { recursive: true });

execFileSync(
  resolve(root, "node_modules", ".bin", "tailwindcss"),
  ["-c", resolve(root, "tailwind.config.cjs"), "-i", resolve(root, "src", "tailwind.css"), "-o", outputCss, "--minify"],
  { cwd: root, env: { ...process.env, BROWSERSLIST_IGNORE_OLD_DATA: "1" }, stdio: "inherit" }
);

const css = readFileSync(outputCss, "utf8");
writeFileSync(outputTs, `// Generated by npm run build:css. Do not edit by hand.\nexport const APP_CSS = ${JSON.stringify(css)};\n`);
